#!/usr/bin/env bash

function ProgressBar {
  let _progress=(${1}*100/${2}*100)/100
  let _done=(${_progress}*4)/10
  let _left=40-$_done
  _fill=$(printf "%${_done}s")
  _empty=$(printf "%${_left}s")

  printf "\rProgress : [${_fill// /#}${_empty// /-}] ${_progress}%%"
}

mkdir -p tmp

protocol=${COUCHDB_PROTOCOL:-http}
username=${COUCHDB_USERNAME:-admin}
password=${COUCHDB_PASSWORD:-password}
host=${COUCHDB_HOST:-localhost}
port=${COUCHDB_PORT:-5984}
database=${1:-database}

echo "Gathering documents..."

if [ ! -f "tmp/${database}.json" ]; then
  echo "Cached database not found, downloading ${database}"
  curl -s -X GET -u ${username}:${password} ${protocol}://${host}:${port}/${database}/_all_docs?include_docs=true > tmp/${database}.json
fi
readarray -t docs < <(cat tmp/${database}.json | jq -c '.rows[] | select( .doc._id | contains("design") | not )' | jq -c '.doc')
echo "Found ${#docs[@]} documents..."
total_ids=${#docs[@]}
count=1
for doc in "${docs[@]}"; do
  square=$(echo "${doc}" | jq -r '.square')
  area=$(echo "${doc}" | jq -r '.area')
  locus=$(echo "${doc}" | jq -r '.code')
  mkdir -p ${database}/${area}/${square}
  echo ${doc} | jq -r '.' > ${database}/${area}/${square}/${locus}.json
  ProgressBar ${count} ${total_ids}
  count=$((count+1))
done

printf '\nFinished!\n'

echo "Zipping ${database}..."
zip -r ${database}_$(date +%Y%m%d).zip ${database}
echo "Cleaning up..."
rm -rf ${database}
echo "Done!"

echo "${database}_$(date +%Y%m%d).zip is ready for achiving."
echo
echo
echo "To do a clean run, delete the tmp directory and run again."